arr = [
    {
        day: "Sunday", eatTime:[
            {eatDuration:"Breakfast", foodType:"Bread"},
            {eatDuration:"Launch", foodType:"Rice"},
            {eatDuration:"Dinner", foodType:"Yam"}
        ] 
    },
    {
        day: "Monday", eatTime:[
            {eatDuration:"Breakfast", foodType:"Beans with bread"},
            {eatDuration:"Launch", foodType:"Bread with Egg"},
            {eatDuration:"Dinner", foodType:"Bread"}
        ] 
    },
    {
        day: "Tuesday", eatTime:[
            {eatDuration:"Breakfast", foodType:"Semo with Eforiro"},
            {eatDuration:"Launch", foodType:"Sandwich"},
            {eatDuration:"Dinner", foodType:"Fried Rice with Chicken"}
        ] 
    },
    {
        day: "Wednesday", eatTime:[
            {eatDuration:"Breakfast", foodType:"Coffee"},
            {eatDuration:"Launch", foodType:"Beans"},
            {eatDuration:"Dinner", foodType:"Potato with Egg"}
        ] 
    },
    {
        day: "Thursday", eatTime:[
            {eatDuration:"Breakfast", foodType:"Bread"},
            {eatDuration:"Launch", foodType:"Bread"},
            {eatDuration:"Dinner", foodType:"Bread"}
        ] 
    },
    {
        day: "Friday", eatTime:[
            {eatDuration:"Breakfast", foodType:"Bread"},
            {eatDuration:"Launch", foodType:"Bread"},
            {eatDuration:"Dinner", foodType:"Bread"}
        ] 
    },
    {
        day: "Saturday", eatTime:[
            {eatDuration:"Breakfast", foodType:"Bread"},
            {eatDuration:"Launch", foodType:"Bread"},
            {eatDuration:"Dinner", foodType:"Bread"}
        ] 
    }
]